[package]
name = "llamix"
version = "0.1.0"
edition = "2021"

[target.x86_64-unknown-linux-musl]
rustflags = ["-C", "target-feature=+crt-static"]
   

[dependencies]
ansi_term = "0.12.1"
json = "0.12.4"
